apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana

resources:
  - operator/
  - grafana-resources.yaml

labels:
  - pairs:
      app: grafana
      component: monitoring

namespace: default
