apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: scheduled-db-monitoring

resources:
  - prometheus/
  - grafana/
  - otel/

labels:
  - pairs:
      monitoring-stack: scheduled-db

namespace: default
