apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus

resources:
  - prometheus-config.yaml
  - prometheus-deployment.yaml

labels:
  - pairs:
      app: prometheus
      component: monitoring

namespace: default
